version: '2'
services:
  coopcycle_jhipster-app:
    image: coopcycle_jhipster
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://coopcycle_jhipster-postgresql:5432/coopcycle_jhipster
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  coopcycle_jhipster-postgresql:
    extends:
      file: postgresql.yml
      service: coopcycle_jhipster-postgresql
